CREATE TABLE IF NOT EXISTS `court_case` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `case_no` varchar(64) NOT NULL COMMENT '案件编号',
  `order_no` varchar(64) NOT NULL COMMENT '订单号',
  `customer_name` varchar(64) NOT NULL COMMENT '客户姓名',
  `mobile` varchar(20) NOT NULL COMMENT '联系电话',
  `amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '涉案金额',
  `repayment_due_date` date DEFAULT NULL COMMENT '应还款日期',
  `current_stage` varchar(32) NOT NULL COMMENT '当前阶段',
  `current_dept_id` bigint DEFAULT NULL COMMENT '当前部门编号',
  `current_assignee_id` bigint DEFAULT NULL COMMENT '当前负责人编号',
  `customer_status` varchar(32) NOT NULL DEFAULT 'PENDING_REPAY' COMMENT '客户状态',
  `last_follow_up_time` datetime DEFAULT NULL COMMENT '最近跟进时间',
  `next_remind_time` datetime DEFAULT NULL COMMENT '下次提醒时间',
  `next_remind_content` varchar(500) DEFAULT NULL COMMENT '下次提醒内容',
  `repaid` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否已还款',
  `repaid_time` datetime DEFAULT NULL COMMENT '还款时间',
  `legal_receiver_id` bigint DEFAULT NULL COMMENT '接收法务人员',
  `transfer_time` datetime DEFAULT NULL COMMENT '移交法诉时间',
  `transfer_recall_deadline` datetime DEFAULT NULL COMMENT '移交撤回截止时间',
  `status` int NOT NULL COMMENT '案件状态',
  `ext_json` text COMMENT '扩展字段 JSON',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_case_no` (`case_no`),
  KEY `idx_current_stage` (`current_stage`),
  KEY `idx_current_dept_id` (`current_dept_id`),
  KEY `idx_current_assignee_id` (`current_assignee_id`),
  KEY `idx_customer_status` (`customer_status`),
  KEY `idx_repayment_due_date` (`repayment_due_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='案件主表';

CREATE TABLE IF NOT EXISTS `court_case_flow_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `case_id` bigint NOT NULL COMMENT '案件编号',
  `action` varchar(64) NOT NULL COMMENT '执行动作',
  `from_stage` varchar(32) DEFAULT NULL COMMENT '原阶段',
  `to_stage` varchar(32) DEFAULT NULL COMMENT '目标阶段',
  `operator_id` bigint NOT NULL COMMENT '操作人编号',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_case_id` (`case_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='案件流转日志表';

CREATE TABLE IF NOT EXISTS `court_case_model` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `version_no` int NOT NULL COMMENT '版本号',
  `status` varchar(16) NOT NULL COMMENT '状态：DRAFT/PUBLISHED/ARCHIVED',
  `change_summary` varchar(500) DEFAULT NULL COMMENT '变更说明',
  `impact_summary` text COMMENT '影响提示',
  `published_time` datetime DEFAULT NULL COMMENT '发布时间',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_case_model_status` (`status`),
  KEY `idx_case_model_version` (`version_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='案件模型版本表';

CREATE TABLE IF NOT EXISTS `court_case_model_field` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `model_id` bigint NOT NULL COMMENT '模型版本编号',
  `field_code` varchar(64) NOT NULL COMMENT '字段编码',
  `field_label` varchar(64) NOT NULL COMMENT '字段名称',
  `field_type` varchar(32) NOT NULL COMMENT '字段类型',
  `required` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否必填',
  `enabled` bit(1) NOT NULL DEFAULT b'1' COMMENT '是否启用',
  `deployed` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否已投产',
  `default_value` varchar(255) DEFAULT NULL COMMENT '默认值',
  `options_json` text COMMENT '选项 JSON',
  `sort_no` int NOT NULL DEFAULT '0' COMMENT '排序',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_case_model_field_model_id` (`model_id`),
  KEY `idx_case_model_field_code` (`field_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='案件模型字段表';

CREATE TABLE IF NOT EXISTS `court_case_follow_up` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `case_id` bigint NOT NULL COMMENT '案件编号',
  `operator_id` bigint NOT NULL COMMENT '跟进人编号',
  `content` varchar(500) NOT NULL COMMENT '跟进内容',
  `attachment_urls` text COMMENT '附件地址，逗号分隔',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_case_follow_up_case_id` (`case_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='案件跟进记录表';

CREATE TABLE IF NOT EXISTS `court_case_reminder` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `case_id` bigint NOT NULL COMMENT '案件编号',
  `reminder_type` varchar(16) NOT NULL COMMENT '提醒类型：MANUAL',
  `remind_time` datetime NOT NULL COMMENT '提醒时间',
  `content` varchar(500) NOT NULL COMMENT '提醒内容',
  `priority` varchar(16) NOT NULL COMMENT '提醒优先级',
  `status` varchar(16) NOT NULL COMMENT '提醒状态：PENDING/DONE/CANCELLED',
  `creator_id` bigint NOT NULL COMMENT '创建人编号',
  `processed_time` datetime DEFAULT NULL COMMENT '处理时间',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_case_reminder_case_id` (`case_id`),
  KEY `idx_case_reminder_time` (`remind_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='案件提醒表';

CREATE TABLE IF NOT EXISTS `court_case_transfer` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `case_id` bigint NOT NULL COMMENT '案件编号',
  `from_user_id` bigint NOT NULL COMMENT '移交人',
  `to_user_id` bigint NOT NULL COMMENT '接收法务人员',
  `reason` varchar(64) NOT NULL COMMENT '移交原因',
  `extra_note` varchar(500) DEFAULT NULL COMMENT '补充说明',
  `status` varchar(16) NOT NULL COMMENT '状态：TRANSFERRED/RECALLED',
  `transfer_time` datetime NOT NULL COMMENT '移交时间',
  `recall_deadline` datetime NOT NULL COMMENT '撤回截止时间',
  `recall_time` datetime DEFAULT NULL COMMENT '撤回时间',
  `recalled_by` bigint DEFAULT NULL COMMENT '撤回人',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_case_transfer_case_id` (`case_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='案件法务移交记录表';
